
const PROVIDERS = [
  {
    name: 'ZEBEDEE',
    image: '/images/zbd.svg',
    imageStyle: { width: '130px', marginTop: '10px', marginBottom: '3px' },
    lightningAddressDomain: 'zbd.gg',
    url: 'https://zbd.gg',
    buttonText: 'Download App',
  },
  {
    name: 'BTCPay Server',
    image: '/images/btcpay.svg',
    imageStyle: { width: '95px' },
    lightningAddressDomain: 'yourbtcpay.server',
    url: 'https://btcpayserver.org/',
  },
  {
    name: 'Bitrefill',
    image: '/images/bitrefill.svg',
    imageStyle: { width: '125px' },
    lightningAddressDomain: 'bitrefill.me',
    url: 'https://bitrefill.com/',
  },
  {
    name: 'LNMarkets',
    image: '/images/lnmarkets.png',
    imageStyle: { width: '125px' },
    lightningAddressDomain: 'lnmarkets.com',
    url: 'https://lnmarkets.com/',
    buttonText: 'Open LN Markets',
  },
  {
    name: 'Strike',
    image: '/images/STRIKE.png',
    imageStyle: { width: '130px' },
    lightningAddressDomain: 'strike.me',
    url: 'https://strike.me/',
    buttonText: 'Download Strike',
  },
  {
    name: 'Coincorner',
    image: '/images/coincorner.svg',
    imageStyle: { width: '130px' },
    lightningAddressDomain: 'coincorner.io',
    url: 'https://coincorner.com/',
  },
  {
    name: 'Bipa',
    image: '/images/bipa.png',
    imageStyle: { width: '45px' },
    lightningAddressDomain: 'bipa.app',
    url: 'https://bipa.app',
    buttonText: 'Download Wallet',
  },
  {
    name: 'FastBitcoins',
    image: '/images/fastbitcoins.png',
    imageStyle: { width: '125px' },
    lightningAddressDomain: 'fbtc.me',
    url: 'https://fastbitcoins.com/',
  },
  {
    name: 'Spark Wallet',
    image: '/images/sparkwallet.svg',
    imageStyle: { width: '125px' },
    lightningAddressDomain: 'sparkwallet.me',
    url: 'https://sparkwallet.io/',
  },
  {
    name: 'coinos',
    image: '/images/coinos.png',
    imageStyle: { width: '130px', marginBottom: '-8px' },
    lightningAddressDomain: 'coinos.io',
    url: 'https://coinos.io',
    buttonText: 'Open Coinos',
  },
  {
    name: '@LightningTipBot',
    image: '/images/lightningtipbot.svg',
    imageStyle: { width: '115px' },
    lightningAddressDomain: 'ln.tips',
    url: 'https://t.me/LightningTipBot',
    buttonText: 'Open Telegram',
  },
  {
    name: 'Blink',
    image: '/images/blink.png',
    imageStyle: { width: '115px' },
    lightningAddressDomain: 'blink.sv',
    url: 'https://blink.sv',
    buttonText: 'Download Wallet',
  },
  {
    name: 'Alby',
    image: '/images/alby.png',
    imageStyle: { width: '44px', paddingBottom: '2px', borderRadius: '5%' },
    lightningAddressDomain: 'getalby.com',
    url: 'https://getalby.com',
  },
  {
    name: 'Wallet of Satoshi',
    image: '/images/wos.svg',
    imageStyle: { width: '105px', paddingBottom: '3px' },
    lightningAddressDomain: 'walletofsatoshi.com',
    url: 'https://walletofsatoshi.com',
    buttonText: 'Download Wallet',
  },
  {
    name: 'Noah',
    image: '/images/noah.png',
    imageStyle: { width: '115px' },
    lightningAddressDomain: 'noah.me',
    url: 'https://app.noah.com',
    buttonText: 'Claim Address',
    comingSoon: false,
  },
  {
    name: 'Bitnob',
    image: '/images/bitnob2.png',
    imageStyle: { width: '115px' },
    lightningAddressDomain: 'bitnob.io',
    url: 'https://bitnob.com',
    buttonText: 'Download Wallet',
  },
  {
    name: 'Bottlepay',
    image: '/images/bottlepay.png',
    imageStyle: { width: '125px' },
    lightningAddressDomain: 'bottlepay.me',
    url: 'https://bottlepay.com',
    buttonText: 'Download Wallet',
  },
  {
    name: 'Machankura',
    image: '/images/machankura.png',
    imageStyle: { width: '45px' },
    lightningAddressDomain: '8333.mobi',
    url: 'https://8333.mobi',
    buttonText: 'Dial Machankura',
    comingSoon: false,
  },
  {
    name: 'Mash',
    image: '/images/mash.svg',
    imageStyle: { width: '125px', marginBottom: '5px' },
    lightningAddressDomain: 'getmash.cash',
    url: 'https://mash.com/consumer-experience/',
  },
  {
    name: 'STARBACKR',
    image: '/images/starbackr.png',
    imageStyle: { width: '130px'},
    lightningAddressDomain: 'starbackr.me',
    url: 'https://app.starbackr.com',
  },
  {
    name: 'Bookmark.org',
    image: '/images/bookmark.png',
    imageStyle: { width: '130px'},
    lightningAddressDomain: 'bookmark.org',
    url: 'https://bookmark.org',
  },
  {
    name: 'LifPay',
    image: '/images/lifpay.png',
    imageStyle: { width: '45px', backgroundColor: 'black', borderRadius: '5%'},
    lightningAddressDomain: 'lifpay.me',
    url: 'https://lifpay.me',
  },
  {
    name: 'Satoshi Lightning',
    image: 'https://vipsats.app/img/satoshi.png',
    imageStyle: { width: '45px', backgroundColor: 'black', borderRadius: '5%'},
    lightningAddressDomain: 'vipsats.app',
    url: 'https://vipsats.app',
  },
  {
    name: 'BitcoLi wallet',
    image: 'https://bitcoli.com/img/logo-40.png',
    imageStyle: { width: '45px', backgroundColor: 'black', borderRadius: '5%'},
    lightningAddressDomain: 'bitcoli.com',
    url: 'https://bitcoli.com',
  },
  {
    name: 'Stakcer News',
    image: '',
    imageStyle: { width: '125px', backgroundColor: 'black', borderRadius: '5%' },
    lightningAddressDomain: 'stacker.news',
    url: 'https://stacker.news',
  }
];
